package internal

var EXTproduction = OMextractors{
	{
		PartPrefixCode: FieldPrefix_ComputedRID,
		FieldIDs:       []string{"C-RID", "C-index"},
	},
	{
		ObjectPath:       "/Radio Rundown/<OM_RECORD>",
		ObjectAttrsNames: []string{"RecordID"},
		PartPrefixCode:   FieldPrefix_RadioRec,
	},
	{
		ObjectPath:     "/*Hourly Rundown",
		FieldsPath:     TemplateHeaderFieldPath,
		FieldIDs:       []string{"8"},
		PartPrefixCode: FieldPrefix_HourlyHead,
	},
	{
		ObjectPath:       "/<OM_RECORD>",
		ObjectAttrsNames: []string{"RecordID"},
		PartPrefixCode:   FieldPrefix_HourlyRec,
	},
	{
		ObjectPath:           "/Sub Rundown",
		ObjectAttrsNames:     []string{"TemplateName"},
		FieldsPath:           TemplateHeaderFieldPath,
		FieldIDs:             ProductionFieldsSubRundown,
		PartPrefixCode:       FieldPrefix_SubHead,
		KeepWhenZeroSubnodes: true,
	},
	{
		ObjectPath:       "/*Radio Story",
		FieldsPath:       TemplateHeaderFieldPath,
		ObjectAttrsNames: []string{"TemplateName"},
		PartPrefixCode:   FieldPrefix_StoryHead,
		// FieldIDs:         []string{"8"},
		FieldIDs: ProductionFieldsRadioStory,
	},
	{
		ObjectPath: "/<OM_RECORD>/Audioclip|Contact Item|Contact Bin",
		// ObjectPath:           "/<OM_RECORD>/Audioclip|Contact Item",
		ObjectAttrsNames:     []string{"TemplateName", "ObjectID"},
		PartPrefixCode:       FieldPrefix_StoryKategory,
		KeepWhenZeroSubnodes: true,
		PreserveParentNode:   true,
		// 251
	},
	{
		ObjectPath: "/Audioclip",
		FieldsPath: TemplateHeaderFieldPath,
		// FieldIDs:   []string{"8"},
		FieldIDs:             ProductionFieldsAudio,
		PartPrefixCode:       FieldPrefix_AudioClipHead,
		KeepWhenZeroSubnodes: true,
		// PreserveParentNode:   true,
	},
	{
		ObjectPath: "/Contact Item|Contact Bin",
		FieldsPath: TemplateHeaderFieldPath,
		// FieldIDs:             []string{"1"},
		FieldIDs:             ProductionFieldsContactItems,
		PartPrefixCode:       FieldPrefix_ContactItemHead,
		KeepWhenZeroSubnodes: true,
	},
	{
		PartPrefixCode: FieldPrefix_ComputedID,
		FieldIDs:       []string{"ID"},
	},
}

// {
// ObjectPath:           "/<OM_RECORD>",
// ObjectAttrsNames:     []string{"RecordID"},
// PartPrefixCode:       FieldPrefix_SubRec,
// KeepWhenZeroSubnodes: true,
// },
// {
// ObjectPath:       "/Radio Story",
// ObjectPath:       "/<OM_RECORD>/Radio Story",
// FieldsPath:       TemplateHeaderFieldPath,
// ObjectAttrsNames: []string{"TemplateName"},
// PartPrefixCode:   FieldPrefix_StoryHead,
// FieldIDs:         []string{"8"},
// FieldIDs: ProductionFieldsRadioStory,
// KeepWhenZeroSubnodes: true,
// },
// {
// ObjectPath:           "/<OM_RECORD>",
// ObjectAttrsNames:     []string{"RecordID"},
// PartPrefixCode:       FieldPrefix_StoryRec,
// KeepWhenZeroSubnodes: true,
// },
// {
// 	// ObjectPath:           "Audioclip|Contact Item",
// 	ObjectPath:           "/<OM_RECORD>/Audioclip|Contact Item",
// 	ObjectAttrsNames:     []string{"TemplateName"},
// 	PartPrefixCode:       FieldPrefix_StoryKategory,
// 	KeepWhenZeroSubnodes: true,
// 	PreserveParentNode:   true,
// },
// {
// 	// ObjectPath: "Audioclip",
// 	ObjectPath: "/<OM_RECORD>/Audioclip",
// 	FieldsPath: TemplateHeaderFieldPath,
// 	FieldIDs:   []string{"8"},
// 	// FieldIDs:             ProductionFieldsAudio,
// 	PartPrefixCode:       FieldPrefix_AudioClipHead,
// 	KeepWhenZeroSubnodes: true,
// 	// PreserveParentNode:   true,
// },
// {
// 	ObjectPath: "/<OM_RECORD>/Contact Item",
// 	FieldsPath: TemplateHeaderFieldPath,
// 	// FieldIDs:             []string{"1"},
// 	FieldIDs:             ProductionFieldsContactItems,
// 	PartPrefixCode:       FieldPrefix_ContactItemHead,
// 	KeepWhenZeroSubnodes: true,
// },
// {
// 	PartPrefixCode: FieldPrefix_ComputedID,
// 	FieldIDs:       []string{"ID"},
// },
//"/Radio Rundown",
//"/Radio Rundown/<OM_RECORD>",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown/<OM_RECORD>",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown/<OM_RECORD>/Sub Rundown",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown/<OM_RECORD>/Sub Rundown/<OM_RECORD>",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown/<OM_RECORD>/Sub Rundown/<OM_RECORD>/Radio Story",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown/<OM_RECORD>/Sub Rundown/<OM_RECORD>/Radio Story/<OM_RECORD>",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown/<OM_RECORD>/Sub Rundown/<OM_RECORD>/Radio Story",
//"/Radio Rundown/<OM_RECORD>/Hourly Rundown/<OM_RECORD>/Radio Story/Contact Item",
