package internal

var EXTproduction = OMextractors{
	{
		ObjectPath:     "/*Hourly Rundown",
		FieldsPath:     TemplateHeaderFieldPath,
		FieldIDs:       []string{"8"},
		PartPrefixCode: FieldPrefix_HourlyHead,
		KeepInputRow:   false,
	},
	{
		ObjectPath: "/<OM_RECORD>",
		FieldsPath: TemplateRecordFieldPath,
		// ObjectAttrsNames: []string{"RecordID"},
		// FieldIDs:         []string{"8"},
		PartPrefixCode: FieldPrefix_HourlyRec,
		KeepInputRow:   false,
	},
	{
		ObjectPath:           "/Sub Rundown",
		ObjectAttrsNames:     []string{"TemplateName"},
		FieldsPath:           TemplateHeaderFieldPath,
		FieldIDs:             ProductionFieldsSubRundown,
		PartPrefixCode:       FieldPrefix_SubHead,
		PreserveParentNode:   true,
		KeepWhenZeroSubnodes: true,
	},
	{
		ObjectPath: "/Sub Rundown/<OM_RECORD>",
		FieldsPath: TemplateRecordFieldPath,
		// ObjectAttrsNames:     []string{"RecordID"},
		PartPrefixCode:       FieldPrefix_SubRec,
		KeepWhenZeroSubnodes: true,
	},
	{
		ObjectPath:     "/Radio Story",
		FieldsPath:     TemplateHeaderFieldPath,
		PartPrefixCode: FieldPrefix_StoryHead,
		FieldIDs:       []string{"8"},
		// KeepWhenZeroSubnodes: true,
	},
	{
		ObjectPath: "/<OM_RECORD>",
		FieldsPath: TemplateRecordFieldPath,
		// ObjectAttrsNames:     []string{"RecordID"},
		PartPrefixCode:       FieldPrefix_StoryRec,
		KeepWhenZeroSubnodes: true,
	},
	{
		ObjectPath:       "/Audioclip",
		ObjectAttrsNames: []string{"TemplateName"},
		FieldsPath:       TemplateHeaderFieldPath,
		// FieldIDs:             ProductionSimpleTest,
		FieldIDs:             ProductionFieldsAudio,
		PartPrefixCode:       FieldPrefix_AudioClipRec,
		KeepWhenZeroSubnodes: true,
		PreserveParentNode:   true,
	},
	{
		ObjectPath:       "/Contact Item",
		ObjectAttrsNames: []string{"TemplateName"},
		FieldsPath:       TemplateHeaderFieldPath,
		// FieldIDs:             ProductionSimpleTest,
		FieldIDs:             ProductionFieldsContactItems,
		PartPrefixCode:       FieldPrefix_ContactItemHead,
		KeepWhenZeroSubnodes: true,
		PreserveParentNode:   true,
	},
}
